theme: jekyll-theme-cayman

# Site settings
name: Kevin Eschbach
description: "Software Engineer"
url: "http://www.kevin-eschbach.de"


# Delete the lines you don't need
email: kevin.eschbach@ruhr-uni-bochum.de
github_username:  kevin-eschbach
linkedin_username: kevin-eschbach

avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars.githubusercontent.com/u/64735549"


front_img: no
# front_img_path: "imgs/background.jpg"

# Build settings
markdown: kramdown
permalink: pretty